### ISSUE TITLE
Add new module: thanks

### ISSUE THREAD

**Issue by swapagarwal** [the-vision/jarvis-telegram#12]
https://github.com/the-vision/jarvis-telegram/wiki

**Comment by VibavariG** [comment]
i would like to work on this issue

**Comment by RohitRathore1** [comment]
@VibavariG Thanks for your interest but at a time in the same repo you can work on one issue only.

**Comment by Shiv1202** [comment]
Sir I would like to work on it.

**Comment by RohitRathore1** [comment]
@Shiv1202  I have assigned this issue to you. Let me know if you need any help!

**Comment by Shiv1202** [comment]
Thanks Sir

**Comment by RohitRathore1** [comment]
@Shiv1202 Are you working on this issue?

**Comment by tanisha03** [comment]
This issue is opened for new assignments now !!!

**Comment by h0m3brew** [comment]
@tanisha03 I would like to work on this issue.

**Comment by RohitRathore1** [comment]
@h0m3brew I have assigned this issue to you. Let me know if you need any help.
