### ISSUE TITLE
Provide an easy way to report an unhandled query

### ISSUE THREAD

**Issue by swapagarwal** [the-vision/jarvis-telegram#13]
Say the user typed 'xyz'. Currently, the bot won't understand the intent behind it and will echo back the input. One possible solution could be to add a button here which opens an issue on the repo with some pre-filled text to report it. Open to hearing other thoughts as well!

**Comment by adityabisoi** [comment]
@swapagarwal I can implement this. Please assign me the issue. Thanks.

**Comment by sgpritam** [comment]
@adityabisoi I have assigned you this issue, let me know if you have any queries.
