### ISSUE TITLE
Add new module : translator

### ISSUE THREAD

**Issue by abnsl0014** [the-vision/jarvis-telegram#21]
https://github.com/the-vision/jarvis-telegram/wiki

**Comment by adityabisoi** [comment]
@abnsl0014 can you please provide more details on its intention?

**Comment by tanisha03** [comment]
@adityabisoi  somethings similar to if some basic words can be translated in some other language, am I right @abnsl0014 ?

**Comment by abnsl0014** [comment]
Yes!, @adityabisoi as @tanisha03 said.

**Comment by adityabisoi** [comment]
Okay @abnsl0014 @tanisha03 can I want to work on this. Please assign me.

**Comment by tanisha03** [comment]
@adityabisoi you can work on it now !!!
