### ISSUE TITLE
bye: fix typo

### ISSUE THREAD

**Issue by swapagarwal** [the-vision/jarvis-telegram#34]
Capitalize the word `have` here: https://github.com/the-vision/jarvis-telegram/blob/master/modules.py#L28
Only for first-time contributors in this repo.

**Comment by dharmykoya** [comment]
Hi, can you grant me access to push to the repository? I have created a branch but I can't push.

thank you.

**Comment by RohitRathore1** [comment]
@dharmykoya you have to just create a PR.
