### ISSUE TITLE
bye: send gif

### ISSUE THREAD

**Issue by swapagarwal** [the-vision/jarvis-telegram#35]
After calling the `reply_to` method, call another method which sends an animated gif to the user here: https://github.com/the-vision/jarvis-telegram/blob/master/modules.py#L32
Reference: https://core.telegram.org/bots/api#sendanimation
Example: `bot.send_animation(message.chat.id, 'https://media.giphy.com/media/UrcXN0zTfzTPi/giphy.gif')`
Only for first-time contributors in this repo.

**Comment by poojasrinivass** [comment]
Can you assign me to work on this issue? I would like to contribute

**Comment by RohitRathore1** [comment]
@poojasrinivass First complete your previous task.

**Comment by poojasrinivass** [comment]
Sure.

**Comment by poojasrinivass** [comment]
I have submitted a PR for my previous issue. Can I work on this now?

**Comment by RohitRathore1** [comment]
@poojasrinivass I have assigned this issue to you. Let me know if you need any help.
