### ISSUE TITLE
coin: flip again

### ISSUE THREAD

**Issue by swapagarwal** [the-vision/jarvis-telegram#37]
Refer the xkcd module and add a similar option to flip the coin again: https://github.com/the-vision/jarvis-telegram/blob/master/modules.py#L11
Only for first-time contributors in this repo.

**Comment by adityabisoi** [comment]
@swapagarwal @TeAmP0is0N Since this issue has been unclaimed, can this be assigned to me?

**Comment by RohitRathore1** [comment]
Go Ahead.
