### ISSUE TITLE
Add new module: bye

### ISSUE THREAD

**Issue by swapagarwal** [the-vision/jarvis-telegram#4]
https://github.com/the-vision/jarvis-telegram/wiki

**Comment by VibavariG** [comment]
I'd like to work on this issue

**Comment by RohitRathore1** [comment]
@VibavariG Thanks for your interest but at a time in the same repo you can work on one issue only.

**Comment by hritikksingh** [comment]
@TeAmP0is0N  I would love to work with this, but before proceeding can you tell me if I can proceed with this if I only know Python.
I have just stared with this project and wanted to contribute to this project.

**Comment by abnsl0014** [comment]
@hritikpapa Yes, you can ! , Just setup it locally - Follow these instructions here-
https://github.com/the-vision/jarvis-telegram/blob/master/SETUP.md 
and you can start contributing.

**Comment by hritikksingh** [comment]
I was still setting it up on my local machine, okay I will start working on it ASAP.

**Comment by hritikksingh** [comment]
I have setup the system locally, Can we discuss about the functionality to add in this.
@swapagarwal @TeAmP0is0N can you suggest me the functionalities to add in this method.
