### ISSUE TITLE
bye: send another gif

### ISSUE THREAD

**Issue by swapagarwal** [the-vision/jarvis-telegram#49]
Add `https://media.giphy.com/media/3o6EhGvKschtbrRjX2/giphy.gif` to the list of gifs and pick one to send randomly.

**Comment by adityabisoi** [comment]
@swapagarwal I can work on this. Please assign it to me. Thanks.

**Comment by Snouzy** [comment]
Hello, i can do that :) ! Thanks

**Comment by RohitRathore1** [comment]
@Snouzy Are you a GSSoC participant?

**Comment by divyaprakashrx** [comment]
@swapagarwal @TeAmP0is0N I want to work on this. Please assign it to me.

**Comment by TeAmP0is0N** [comment]
@divyaprakash-Rx I have assigned this issue to you. Let me know if you need any help.

**Comment by divyaprakashrx** [comment]
Ok

**Comment by divyaprakashrx** [comment]
@TeAmP0is0N Please review pull request.
