### ISSUE TITLE
Add new module: coin

### ISSUE THREAD

**Issue by swapagarwal** [the-vision/jarvis-telegram#5]
https://github.com/the-vision/jarvis-telegram/wiki

**Comment by vvijayalakshmi21** [comment]
Hi, Can i take this up?

**Comment by RohitRathore1** [comment]
@vvijayalakshmi21 Thanks for your interest but at a time in the same repo you can work on one issue only.

**Comment by adityabisoi** [comment]
@TeAmP0is0N I want to work on this issue. Please assign me.

**Comment by RohitRathore1** [comment]
@adityabisoi I have assigned this issue to you. Let me know if you need any help.
