### ISSUE TITLE
Add new intent: news

### ISSUE THREAD

**Issue by swapagarwal** [the-vision/jarvis-telegram#56]
https://github.com/the-vision/jarvis-telegram/wiki

Maybe use Inshorts api.

**Comment by aditianshu** [comment]
Could I work on this issue?

**Comment by RohitRathore1** [comment]
@aditianshu Are you the participant of GSSoC?

**Comment by adityabisoi** [comment]
@TeAmP0is0N @swapagarwal I can work on this. Please assign me this.

**Comment by RohitRathore1** [comment]
@adityabisoi Go ahead. :)
