### ISSUE TITLE
Add new module: fact

### ISSUE THREAD

**Issue by swapagarwal** [the-vision/jarvis-telegram#6]
https://github.com/the-vision/jarvis-telegram/wiki

**Comment by InfiniteVerma** [comment]
I'll like to work on this.

**Comment by RohitRathore1** [comment]
@InfiniteVerma  I have assigned this issue to you. Let me know if you need any help!

**Comment by InfiniteVerma** [comment]
I got the playground bot working. So do you wish to have a fact brought from an api? For instance, I found this http://numbersapi.com/

**Comment by abnsl0014** [comment]
@InfiniteVerma Yes!, you can use API's for implementing various functionalities.
