### ISSUE TITLE
Add config file

### ISSUE THREAD

**Issue by adityabisoi** [the-vision/jarvis-telegram#61]
The project should have a config file for storing all confidential key data. 

@TeAmP0is0N @swapagarwal I can do this.

**Comment by swapagarwal** [comment]
@adityabisoi Which data are you referring to?

**Comment by adityabisoi** [comment]
@swapagarwal API keys, and probably database credentials in the future? The dictionary module requires a WORDS API. New modules which make API calls may have their keys too.

**Comment by swapagarwal** [comment]
We have an `.env` file for that, no?

**Comment by adityabisoi** [comment]
YUP, my bad!
Closing this issue.
