### ISSUE TITLE
Add new module: Anime

### ISSUE THREAD

**Issue by RohitRathore1** [the-vision/jarvis-telegram#69]
https://github.com/the-vision/jarvis-telegram/wiki

**Comment by Pihu1998** [comment]
Hi @TeAmP0is0N . I am a Gssoc'20 participant. Can I be assigned to this issue, please?

**Comment by RohitRathore1** [comment]
@Pihu1998 Please solve previously assigned issue, then you can work on it.

**Comment by adityabisoi** [comment]
@TeAmP0is0N I want to work on this issue. Please assign this to me.

**Comment by RohitRathore1** [comment]
@adityabisoi  Go ahead.
