### ISSUE TITLE
Add new module: hello

### ISSUE THREAD

**Issue by swapagarwal** [the-vision/jarvis-telegram#7]
https://github.com/the-vision/jarvis-telegram/wiki

**Comment by adityabisoi** [comment]
Hello @swapagarwal , I want to work on this. Please assign this to me. Thanks.

**Comment by RohitRathore1** [comment]
> Hello @swapagarwal , I want to work on this. Please assign this to me. Thanks.

@adityabisoi I have assigned this issue to you. Let me know if you need any help!

**Comment by adityabisoi** [comment]
@TeAmP0is0N can you please help me with the credentials in ```.env``` file? I do not quite get ```CONFIDENCE_THRESHOLD``` , ```FALLBACK_INTENT``` and ```MIND_STONE```

**Comment by RohitRathore1** [comment]
@adityabisoi , we are working on simplifying the credentials. We'll let you know once it's done.

**Comment by swapagarwal** [comment]
@adityabisoi You can test out the bot here: https://github.com/the-vision/jarvis-telegram-playground
Once it's working, just add the corresponding code to `modules.py`.
