### ISSUE TITLE
Add new module: joke

### ISSUE THREAD

**Issue by swapagarwal** [the-vision/jarvis-telegram#9]
https://github.com/the-vision/jarvis-telegram/wiki

**Comment by vvijayalakshmi21** [comment]
Hi, Can i take this up?

**Comment by abnsl0014** [comment]
I have assigned you this issue, let me know if you have any queries.

**Comment by RohitRathore1** [comment]
@vvijayalakshmi21 Thanks for your interest but at a time in the same repo you can work on one issue only.

**Comment by adityabisoi** [comment]
@TeAmP0is0N @swapagarwal  I want to work on this. Please assign me.

**Comment by RohitRathore1** [comment]
@adityabisoi I have assigned this issue to you. Let me know if you need any help!
